### ISSUE TITLE
Don’t forget the web.config

### ISSUE THREAD

**Issue by aarongustafson** [lukechilds/tor-explorer#1]
Here’s the template for Node: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by lukechilds** [comment]
@aarongustafson thanks.

Sorry I'm not familiar with Azure, I've literally just plonked that in the root and renamed to `web.config`. That's enough right? Should I be using something like `forever` in my `npm start` script or does iisnode handle all that?

**Comment by aarongustafson** [comment]
I think IIS will handle that, but I will deploy and we can see where we’re
at.

**Comment by lukechilds** [comment]
@aarongustafson Do you need me to do anything else?

**Comment by aarongustafson** [comment]
I think we’re good.
